#服务器接口配置
server:
  port: 9090
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
  servlet:
    session:
      cookie:
        name: UISESSIONMEMBER
      timeout: 30
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_boot_example?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root

  redis:
    url: redis://123456w@alpha.zyyl.redis01.srv:6378/6?timeout=5s&database=6
    database: 6

logging.level.org.springframework.security: DEBUG
log:
  path: ${user.home}/logs/applogs/oauth_server
  level: info

