spring:
  application:
    name: oauth_server_text
  devtools:
    restart:
      log-condition-evaluation-delta: false
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  thymeleaf:
    cache: false
    suffix: ".html"
    prefix: classpath:/templates/
    mode: HTML5
    encoding: UTF-8
    enabled: true
    check-template: true
    check-template-location: true
    servlet:
      content-type: text/html
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/spring_boot_example?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root


  redis:
    url: redis://123456w@alpha.zyyl.redis01.srv:6378/6?timeout=5s

server:
  port: 7070
  tomcat.max-threads: 0
  tomcat.uri-encoding: UTF-8
  servlet:
    session:
      cookie:
        name: UISESSIONMEMBER
      timeout: 30



logging.level.org.springframework.security: DEBUG




management:
  endpoint:
    shutdown:
      enabled: true


  endpoints:
    web:
      exposure:
        include: info, health, shutdown

